trigger:
- main

pool:
  name: 'pol10'

steps:

- checkout: self

- script: mvn clean package
  displayName: 'Build Maven Project'

- script: |
    echo "Simulating deployment..."
    mkdir deployed
    copy target\*.jar deployed\
    echo "Deployment successful!"
  displayName: 'Simulate Deployment'

- script: |
    echo "Contents of deployed folder:"
    dir deployed
  displayName: 'Verify Deployment Output'