trigger:
- main

pool:
  name: 'pol10'

steps:

- checkout: self

- script: mvn clean package
  displayName: 'Build Maven Project'

- script: |
    echo "Simulating deployment..."
    if not exist deployed mkdir deployed
    copy target\*.jar deployed\
    echo "Deployment successful!"
  displayName: 'Simulate Deployment'

- script: |
    echo "Running the JAR file..."
    java -jar deployed\*.jar
  displayName: 'Run Application'